lit_file = "chapters/literature_survey.tex"

content = """
\\section{Exhaustive Review of Historical Paradigms and Benchmark Studies}

\\subsection{The Hidden Markov Model (HMM) Era (1990s - 2000s)}
In the early days of offline handwriting recognition, before the advent of high-performance GPUs and large-scale labeled datasets, Hidden Markov Models (HMMs) dominated the landscape. An HMM models a sequence of observable events (the handwritten strokes or image slices) as being generated by a sequence of hidden states (the underlying characters).

A seminal paper by Marti and Bunke (2001) introduced the IAM Handwriting Database, which became the de facto benchmark for the field. Their baseline system utilized a sliding window approach, extracting 9 geometric features per window (e.g., fraction of black pixels, center of gravity, second-order moments). The emission probabilities for the HMM were modeled using Gaussian Mixture Models (GMMs). Given a hidden state $s_j$ and an observation vector $x_t$, the emission probability is:
\\begin{equation}
    b_j(x_t) = \\sum_{m=1}^M c_{jm} \\mathcal{N}(x_t | \\mu_{jm}, \\Sigma_{jm})
\\end{equation}
where $M$ is the number of Gaussian mixtures, $c_{jm}$ is the mixture weight, and $\\mathcal{N}$ is the multivariate normal distribution with mean $\\mu_{jm}$ and covariance $\\Sigma_{jm}$.

While this mathematical framework was elegant and probabilistic, it suffered from severe limitations:
1. \\textbf{Feature Engineering:} The 9-dimensional handcrafted features were highly sensitive to pen thickness and slant variations.
2. \\textbf{Markov Assumption:} HMMs assume that the current state depends only on the immediate previous state (first-order Markov property), failing to capture long-range visual dependencies (e.g., crossing a 't' several pixels after the vertical stroke).

\\subsection{The CNN-RNN Hybrid Revolution (2015 - 2018)}
The transition to deep learning eliminated handcrafted features. Shi et al. (2017) published a landmark paper introducing the Convolutional Recurrent Neural Network (CRNN). The CRNN architecture treated the image as a sequence of vertical feature columns, extracting them using a VGG-style CNN, and passing them into a BiLSTM.

The critical mathematical innovation enabling this end-to-end training without explicit character-level bounding boxes was the Connectionist Temporal Classification (CTC) loss, originally formulated by Alex Graves in 2006. By summing over all possible alignments between the unsegmented input sequence and the target label, CTC allowed the network to learn character boundary localizations implicitly. Let $S$ be the set of training examples, then the CRNN objective was to minimize the negative log-likelihood:
\\begin{equation}
    O = - \\sum_{(x, z) \\in S} \\ln p(z | x)
\\end{equation}
This architecture became the standard for both Scene Text Recognition (STR) and Handwritten Text Recognition (HTR).

\\section{Exhaustive Breakdown of Attention Varieties}
Following the success of sequence-to-sequence models in Neural Machine Translation, researchers began applying attention mechanisms to HTR to overcome the alignment rigidity of CTC.

\\subsection{Bahdanau (Additive) Attention}
Introduced by Bahdanau et al. (2015), additive attention calculates an alignment score $e_{t,i}$ between the decoder hidden state $s_{t-1}$ and the encoder hidden state $h_i$ using a feed-forward neural network:
\\begin{equation}
    e_{t,i} = v_a^T \\tanh(W_a s_{t-1} + U_a h_i)
\\end{equation}
These scores are normalized via softmax to produce attention weights $\\alpha_{t,i}$, which are then used to compute the context vector $c_t = \\sum_i \\alpha_{t,i} h_i$. This allowed the decoder to "look back" at specific parts of the image when generating each character. However, Bahdanau attention is computationally expensive because the alignment model must be evaluated for every encoder-decoder state pair.

\\subsection{Luong (Multiplicative) Attention}
Luong et al. (2015) proposed a computationally lighter alternative by using dot-product or bilinear formulations for the alignment score:
\\begin{equation}
    e_{t,i} = s_{t-1}^T W_a h_i
\\end{equation}
This matrix multiplication is highly optimized on modern GPUs, drastically reducing inference latency compared to the additive MLP approach. In the context of HTR, multiplicative attention excels at aligning crisp, printed text but sometimes struggles with the highly distorted, overlapping strokes of cursive handwriting where additive attention's non-linearity provides an edge.

\\subsection{Self-Attention and Vision Transformers (ViT)}
The most recent paradigm shift involves abandoning recurrence entirely in favor of self-attention, as popularized by the Transformer architecture (Vaswani et al., 2017). The Vision Transformer (ViT) splits the word image into non-overlapping patches (e.g., $16 \\times 16$ pixels), linearly embeds them, adds positional encodings, and processes them through multi-head self-attention layers:
\\begin{equation}
    \\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V
\\end{equation}
Models like TrOCR (Transformer-based Optical Character Recognition) utilize a ViT encoder and a RoBERTa-style text decoder. While Transformers achieve state-of-the-art accuracy by capturing global image context simultaneously, they require vastly more training data than CNN-BiLSTM hybrids and suffer from quadratic memory complexity $\\mathcal{O}(N^2)$ with respect to the sequence length, making them difficult to deploy on memory-constrained edge devices for long paragraph transcription.
"""

with open(lit_file, "a", encoding="utf-8") as out_f:
    out_f.write(content)

print("Expanded literature with deep paper reviews and attention breakdown.")
